name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build-user:
    name: Build User App APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./mizofy-tv-user
        run: npm install

      - name: Generate Android project
        working-directory: ./mizofy-tv-user
        run: npx expo prebuild --platform android --no-install

      - name: Build APK with Gradle
        working-directory: ./mizofy-tv-user/android
        run: ./gradlew assembleRelease

      - name: Upload User APK
        uses: actions/upload-artifact@v4
        with:
          name: Mizofy-User-APK
          path: mizofy-tv-user/android/app/build/outputs/apk/release/app-release.apk

  build-admin:
    name: Build Admin App APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./mizofy-tv-admin/mizofy-tv-app
        run: npm install

      - name: Generate Android project
        working-directory: ./mizofy-tv-admin/mizofy-tv-app
        run: npx expo prebuild --platform android --no-install

      - name: Build APK with Gradle
        working-directory: ./mizofy-tv-admin/mizofy-tv-app/android
        run: ./gradlew assembleRelease

      - name: Upload Admin APK
        uses: actions/upload-artifact@v4
        with:
          name: Mizofy-Admin-APK
          path: mizofy-tv-admin/mizofy-tv-app/android/app/build/outputs/apk/release/app-release.apk
